FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
COPY infra/server.sh server.sh

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 5000

RUN chmod +x server.sh
ENTRYPOINT ["./server.sh"]