#!/bin/bash

export MLFLOW_SERVER_ALLOWED_HOSTS=$MLFLOW_ALLOWED_HOSTS
export MLFLOW_BACKEND_STORE_URI=$POSTGRESQL_URL
export MLFLOW_ARTIFACTS_DESTINATION=$STORAGE_URL
export MLFLOW_HOST=0.0.0.0
export MLFLOW_PORT=5000

exec mlflow server